# -*- coding: utf-8 -*-
"""Python Fundamental for Data Science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCld_-CgRe0SjA_ZvsBrfiklesMJgNqX

Buatlah sebuah program yang dapat menentukan suatu variabel apakah merupakan bilangan genap atau ganjil. Lakukan percobaan dengan langkah berikut:

Buat variabel dengan nama “angka” yang diisi dengan nilai 10
Ganti bagian … dengan perhitungan untuk menentukan angka modulus 2 bernilai 0.
Jika angka bernilai genap maka keluarkan "angka termasuk bilangan genap". Selanjutnya, ganti nilai variable angka dengan nilai 5 dan ceklah kembali apakah angka bernilai ganjil. Jika iya, keluarkan "angka termasuk bilangan ganjil".
"""

# Langkah 1: Buat variabel "angka" dengan nilai 10
angka = 5

# Langkah 2: Cek apakah angka genap (modulus 2 == 0)
if angka % 2 == 0:
    print("angka termasuk bilangan genap")
else:
    print("angka termasuk bilangan ganjil")

# Langkah 3: Ganti nilai variabel "angka" menjadi 5